service: techy-brekky

provider:
  name: aws
  runtime: nodejs8.10
  stackTags:
      project: "techy-brekky"
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt:
          - ordersTable
          - Arn
        - { "Fn::Join": [ '/', [{ "Fn::GetAtt": ['ordersTable', "Arn" ] }, "index", "UserOrders" ]]}


functions:
  create:
    handler: orders.create
    events:
    - http:
        path: orders
        method: post
  get:
    handler: orders.get
    events:
    - http:
        path: orders
        method: get
  delete:
    handler: orders.delete
    events:
    - http:
        path: orders
        method: delete

resources:
  Resources:
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: Username
            AttributeType: S
          - AttributeName: BreakfastId
            AttributeType: N
        KeySchema:
          - AttributeName: BreakfastId
            KeyType: HASH
          - AttributeName: Username
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: UserOrders
            KeySchema:
              - AttributeName: Username
                KeyType: HASH
              - AttributeName: BreakfastId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
